# Generated by Django 3.2.3 on 2021-05-22 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to=users.models.user_avatar_path)),
                ('surname', models.CharField(blank=True, max_length=35)),
                ('first_name', models.CharField(blank=True, max_length=35)),
                ('birth_day', models.DateField(blank=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Controler'), (3, 'polyvalent')])),
                ('tel', models.CharField(blank=True, max_length=10)),
                ('address_street', models.CharField(blank=True, db_column='UserAddressStreet', max_length=200)),
                ('address_postal_code', models.CharField(blank=True, db_column='UserAddressPostalCode', max_length=10)),
                ('address_city', models.CharField(blank=True, db_column='UserAddressCity', max_length=30)),
                ('address_country', models.CharField(blank=True, default='France', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
